spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/lab-master?characterEncoding=utf-8
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.czh.labmaster.*
      filters:  stat,wall,slf4j

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000
          logSlowsql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: 3

  mvc:
    hiddenmethod:
      filter:
        enabled: true